services:
    # Laravel App
    app:
        build:
            context: "./"
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "${APP_PORT:-8000}:80"
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        networks:
            - app-network
        depends_on:
            - mysql
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=tables_reservations
            - DB_USERNAME=root
            - DB_PASSWORD=rootpassword

    # MySQL Database
    mysql:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: tables_reservations
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8080:80"
        networks:
            - app-network

# Volumes to persist data
volumes:
    mysql-data:

# Networks
networks:
    app-network:
        driver: bridge
